### ISSUE TITLE
Programa stringa su "Daroma duomenų analizė..."

### ISSUE THREAD

**Issue by kranux** [arnas/tracking-virus-not-people#1]
Sveiki, gera iniciatyva!

Pabandžiau patestuoti, įkėliau failą, liko suktis "Daroma duomenų analizė.."

JS consolėje: 

```
main.4b762e86.chunk.js:formatted:551 Uncaught (in promise) TypeError: Cannot read property 'score' of undefined
    at me (main.4b762e86.chunk.js:formatted:551)
    at main.4b762e86.chunk.js:formatted:586
    at l (2.fd9b1641.chunk.js:2)
    at Generator._invoke (2.fd9b1641.chunk.js:2)
    at Generator.forEach.e.<computed> [as next] (2.fd9b1641.chunk.js:2)
    at r (2.fd9b1641.chunk.js:2)
    at s (2.fd9b1641.chunk.js:2)
```

Kas veda čia:               `, v = .7 * (.7 * y[0].score + .2 * y[1].score + .1 * y[2].score)`
Ir čia: https://github.com/arnas/tracking-virus-not-people/commit/a32c9cf1def90fb7a48a3087fde9d6a2b7b6c7ad#diff-9240cc8560f94a9f2cf206fe9f7418aeL111

**Comment by arnas** [comment]
Labas, ačiū už pranešimą. Padarėme fix'ą tai turėtu strigimo nebebūti, o jei kažkas nutiktų - gražiai parodytų klaidos žinutę.

**Comment by kranux** [comment]
Dėkui už greitą reakciją! :)
